// Operator-authorized execution without model-authored checking ceremony.
export function leanMission({ role, reportPath, previous, task, directory, contract, project }) {
  const bf2 = project.name === 'bf2';
  return `${contract}

ROLE: ${role}. Owner: ${project.root}. Run directory: ${directory}.
Previous report: ${previous ?? 'none'}.
${role === 'planner'
    ? `Trust the preceding report and saved results. Select exactly one remaining ${bf2 ? 'outcome-advancing' : 'content-producing'} task. Read only the progress/inputs needed to select it. Do not review completed work, inspect receipts, audit coverage, assign verification/repair passes, or pull methodologies. ${bf2 ? 'Return ready_for_user_test only with actual launch and offline game UI evidence plus a reproducible launch_command; process survival and completed tree cleanup are not readiness.' : `If this lane's content is finished, return ${project.ready}.`}`
    : `Assigned task: ${JSON.stringify(task)}. Do only its unfinished ${bf2 ? 'authorized research, experiment or content work' : 'content-producing work'}. Earlier reports and the latest saved packet/artifact are trusted checkpoints. If comparison, reading or writing is already reported complete, do not repeat it. If only old checking/verification remains, finish the result/report without performing those checks.`}

CURRENT AUTHORITY OVERRIDES ALL OLDER TASKS, ACCEPTANCE TEXT AND CHECKPOINT TODO LISTS:
No checking, verification, independent validation, hash/token/receipt audits, integrity sweeps, forcing/repair passes, protocol pulls or post-write readbacks. Do not read Canopy, Commit, Project Rules, Dialogue, Forcing Pass, Persistence or linked procedure children. Do not re-prove previous work. Read source material only for analysis that has not already been done; read existing destination content only when needed to preserve/update it. Trust recorded reads, comparisons, links and writes. A named landed node is already created: never recreate it. Do not let old verification prerequisites block advancement. This does not authorize inventing results or discarding existing content.

${bf2 ? 'BF2 SAFETY AND EXPERIMENT EVIDENCE ARE NOT CEREMONY: preserve the unmodified retained baseline and existing tighter authorization limits. Before an authorized game/Wine launch or mutation, establish baseline identity and use a recoverable disposable copy/prefix; skip repeated custody/hash sweeps on tree-only work. Record actual experiment observations, launch/UI evidence and process cleanup. Do not repeat an experiment to review an already reported result. No root, host-security changes, retained-original mutations or new authorization. Jack owns the final play test.' : "For founder evidence, all project work and unnamed people/users/founders in Jack's source trees are Jack unless someone else is explicitly named. Treat his ownership statement as given; no authorship/identity audits or proof requests. Preserve explicitly named other people's contributions. This does not rename the speakers in the supplied YC videos."}

OPERATIONAL RECOVERY IS PREAUTHORIZED, NOT A CONTENT AUDIT: do not ask Jack to resolve transient tool failures. For a timed-out write, use only a narrow delivery lookup for the unique submitted marker/text; if absent, retry the exact saved payload, never a confirmed write. Use pipeline_mode:true wherever supported to avoid propagation validation and connected-context expansion. This exception does not permit source re-verification or content review. Preserve payloads and delivery state; continue recovery without new human approval. Operator-provided recovery results override older unknown-delivery blockers. If transient recovery remains unfinished, return continue with the exact recovery action rather than asking Jack for permission. ${bf2 ? 'Stop at a real authority/safety blocker or the ready_for_user_test boundary.' : 'Stop before the live interview only when the preparation work is finished.'}

At the 80% friendly stop, save completed work, landed node IDs, remaining content work and the next action. Return continue. The successor reads this checkpoint and continues, not restarts. Never replay completed actions or spend an already-used launch budget. Respect operator stops and the original write boundaries. No child agents, model changes, web, outreach, submission or human interviews.

Write JSON in place to the reserved ${reportPath}: version:1, role:${JSON.stringify(role)}, disposition, summary, evidence:absolute-artifact-path[], updated_nodes:UUID[]. Include remaining_work and next_bounded_action when unfinished. Planner dispositions: next with task:{instruction:string,acceptance:string${project.name === 'yc-profile' ? ',tree_id:string' : ''}}, ${project.ready}, blocked, continue. Worker dispositions: worked, blocked, continue${project.excludeUnreadable ? ', excluded for denied AI tree access' : ''}. ${bf2 ? 'Report actual changed node IDs only; updated_nodes may be empty when no new write is needed. ready_for_user_test requires launch_command:string and at least two existing evidence files: the actual launch log and actual offline game UI evidence.' : 'Reader reports also include matching tree_id and tree_packet (an absolute file-path STRING, not an embedded object; save content to that packet file); profile task/report identifies its assigned tree_id. Ready reports name the final content/progress artifacts and existing profile/finding owner IDs, not validator artifacts.'}
report_outcome describes delivery to the controller, not completion of the assignment. After writing a worked, continue, excluded or blocked report and draining any tracked background work, call report_outcome({outcome:"completed",summary:"..."}) and end the turn. Unfinished work uses disposition continue plus outcome completed; a real prerequisite uses blocked plus completed. Do not read back the report or perform a final check. Use outcome failed only when no report can be delivered.`;
}
