export function sizeMission({ role, reportPath, previous, task, directory, contract, project }) {
  return `${contract}

ROLE: ${role}; exclusive assignment: ${JSON.stringify(task)}.
Run directory: ${directory}. Previous checkpoint: ${previous ?? 'none'}.
Use the task's previous_checkpoint when supplied, then the controller checkpoint above. Trust recorded completed reading, grouping, created IDs and successful writes. Continue only unfinished work; never recreate a landed child or replay a confirmed append. The controller selects owners from a fixed queue; do not select successors, review old branches, or run a planner/reviewer phase.

Current authority: Jack requested sequential Luna/high workers, an 80% friendly stop, and NO CHECKING OR VERIFICATION. This overrides older mission/checkpoint TODOs requiring audit, review, forcing/repair/Verify passes, post-write readbacks, hashes, payload comparisons, full-branch recounts or final validation. Commit/Project Rules remain structural guidance, not permission to reinstate their checking phases or human approval stops. Count only prepared crystallization strings using uv/tiktoken o200k_base so every submitted body is strictly below 5,000; this drafting constraint is not a post-write audit. Use the SiftText CLI exclusively. Do not use rendered XML or whole-node self_tokens as the draft count. No nested agents, model/route changes, web, outreach or application/interview work.

Read current node content only when needed for preservation and decomposition. Raw CLI replies stay on disk; load complete relevant owner fields without incidental connected-context expansion. Immutable originals are backups, not a second required read or permission to overwrite newer text. Choose meaningful outcome/question children using the existing content and requested structural rules. Preserve detailed episodes, source links, qualifications, counterevidence and pending questions on the tree before shrinking original owners. Keep original UUIDs useful. No arbitrary numbered token chunks, invented findings, loss of source wording, or relocating detail into unbounded scopes to evade the crystallization limit. Previously completed owners remain completed. If task.hub is true, earlier trait work has finished; this last hub task can place its retained material within the Profile branch as needed, keeping every prepared affected body below the limit.

Use pipeline_mode:true for supported mutation tools; trust successful responses. For ambiguous delivery only, use a narrow submitted-marker lookup to avoid duplicating a timed-out write, then retry the identical missing payload. Recover ordinary tool failures autonomously rather than ask Jack. No content/source re-verification.

At the actual 80% friendly stop, stop substantive work, save exact completed/unfinished steps, created IDs, source/payload files and uncertain deliveries. Return disposition continue. The controller launches a fresh ${project.route.model}/${project.route.thinking} worker for this SAME owner and checkpoint. No compaction or rollover packet. No arbitrary time/token budget or voluntary method-only checkpoint while capacity remains. On finishing the owner, return worked without any closing check/readback; the controller advances to the next owner.

Write JSON in place to ${reportPath}: version:1, role:${JSON.stringify(role)}, disposition:worked|continue|blocked, summary, owner_id:${JSON.stringify(task?.owner_id)}, evidence:absolute-existing-artifact-path[], updated_nodes:actual-UUID[]. Evidence is the saved delta/payload/progress/prepared-count artifacts, not verification output. Include remaining_work and next_bounded_action on continue, and any unconfirmed deliveries. The launcher already reserved this report inode. Deliver via bash using Node fs.openSync(reportPath,'r+'), fs.writeFileSync(fd,JSON.stringify(report)), fs.ftruncateSync(fd,Buffer.byteLength(JSON.stringify(report))), fs.fsyncSync(fd), fs.closeSync(fd), or equivalent uv/Python open(...,'r+') plus truncate/flush/fsync. Do NOT use an atomic-save/rename helper, replace the file, or use a write tool that may replace its inode. Prepared JSON can be an ordinary separate artifact; only the reserved report must retain its inode. Do not read it back. After saving the report and draining tracked background work call report_outcome({outcome:"completed",summary:"..."}) and end the turn. This delivers a continue report without falsely completing its owner. Use blocked only for an actual permission/safety prerequisite, not unfinished work or transient recovery; failed only if no report can be delivered.`;
}
